name: Deploy on server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 52.0.87.119
          username: admin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd carat-gold/service
            git pull origin main
            go install
            go build
            pm2 restart carat-gold
            cd metatrader
            go install
            go build
            pm2 restart metatrader
            cd ..
            pm2 restart api_history
            pm2 start history/api.py --interpreter=python3 --name=api_history

